apiVersion: batch/v1
kind: Job
metadata:
  name: robot-framework-batchjob
spec:
  template:
    spec:
      volumes:
        - name: cert
          secret:
            secretName: minio-crt
      restartPolicy: Never
      containers:
        - name: robot-framework-batchjob
          env:
            - name: WEBSITE_URL
              value: http://nginx-service:8080
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: root-user
                  name: minio
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: minio
          image: ghcr.io/johannessarpola/k8s-nginx-robottests:1.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: cert
              mountPath: "/certs/ca.crt"
              subPath: ca.crt
  backoffLimit: 0
  
