apiVersion: batch/v1
kind: CronJob
metadata:
  name: robot-framework-cronjob
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
      spec:
        template:
          spec:
            volumes:
              - name: cert
                secret:
                  secretName: minio-crt
            restartPolicy: Never
            containers:
              - name: robot-framework-cronjob
                env:
                  - name: WEBSITE_URL
                    value: http://nginx-service:8080
                  - name: MINIO_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        key: root-user
                        name: minio
                  - name: MINIO_SECRET_KEY
                    valueFrom:
                      secretKeyRef:
                        key: root-password
                        name: minio
                image: ghcr.io/elisapolystar/poc-k8s-robottests-nginx:1.0
                imagePullPolicy: IfNotPresent
                volumeMounts:
                  - name: cert
                    mountPath: "/certs/ca.crt"
                    subPath: ca.crt
